// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNTNmQNEl58DBsJsdMGcgXTwwDyqd5p8',
    appId: '1:1020052408808:web:3ba865c59f60ba9cbc3c5d',
    messagingSenderId: '1020052408808',
    projectId: 'parcial-final-b5832',
    authDomain: 'parcial-final-b5832.firebaseapp.com',
    storageBucket: 'parcial-final-b5832.firebasestorage.app',
    measurementId: 'G-TVLCX85M6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_zjX8FRGoIrWa_ySeieAW4CxNhHWlqo',
    appId: '1:1020052408808:android:b3c3e597dc0b75f0bc3c5d',
    messagingSenderId: '1020052408808',
    projectId: 'parcial-final-b5832',
    storageBucket: 'parcial-final-b5832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1elkVEt8Yt7mJh9057UycBw2vfP7y9o',
    appId: '1:1020052408808:ios:0388b12d6390e3e1bc3c5d',
    messagingSenderId: '1020052408808',
    projectId: 'parcial-final-b5832',
    storageBucket: 'parcial-final-b5832.firebasestorage.app',
    iosBundleId: 'com.example.parcial02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1elkVEt8Yt7mJh9057UycBw2vfP7y9o',
    appId: '1:1020052408808:ios:0388b12d6390e3e1bc3c5d',
    messagingSenderId: '1020052408808',
    projectId: 'parcial-final-b5832',
    storageBucket: 'parcial-final-b5832.firebasestorage.app',
    iosBundleId: 'com.example.parcial02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNTNmQNEl58DBsJsdMGcgXTwwDyqd5p8',
    appId: '1:1020052408808:web:5c7bdbc8b5311cb4bc3c5d',
    messagingSenderId: '1020052408808',
    projectId: 'parcial-final-b5832',
    authDomain: 'parcial-final-b5832.firebaseapp.com',
    storageBucket: 'parcial-final-b5832.firebasestorage.app',
    measurementId: 'G-CZGH5CW5EP',
  );
}
